from __future__ import annotations

import base64
import json
import os
import socket
import time
from pathlib import Path

HOST = "127.0.0.1"
PORT = 49491
EXPECTED_BRIDGE_VERSION = "0.9.51"
EXPECTED_BRIDGE_BUILD_ID = "stage5d29-point-cloud-default-20260815a"


AUTO_STARTUP_FILENAME = "ForestManager_AutoBridge.ms"


def _maxscript_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _startup_loader_text(bridge_path: Path) -> str:
    escaped = _maxscript_string(str(bridge_path))
    return (
        "-- Forest Manager automatic bridge loader. Generated by runtime_bridge.py.\n"
        "try\n"
        "(\n"
        f'    local fmBridgePath = "{escaped}"\n'
        "    if doesFileExist fmBridgePath then\n"
        "        fileIn fmBridgePath quiet:true\n"
        "    else\n"
        '        format "Forest Manager bridge not found: %\\n" fmBridgePath\n'
        ")\n"
        "catch\n"
        "(\n"
        '    format "Forest Manager auto bridge load failed: %\\n" (getCurrentException())\n'
        ")\n"
    )


def install_startup_bridge_loader() -> list[Path]:
    """Install/update the 3ds Max per-user startup loader for every detected Max profile."""
    local_appdata = os.environ.get("LOCALAPPDATA", "").strip()
    if not local_appdata:
        return []

    profiles_root = Path(local_appdata) / "Autodesk" / "3dsMax"
    if not profiles_root.is_dir():
        return []

    bridge_path = project_root() / "maxscripts" / "ForestManager_Bridge.ms"
    if not bridge_path.is_file():
        raise RuntimeError("Forest Manager bridge file not found: " + str(bridge_path))

    loader_text = _startup_loader_text(bridge_path)
    installed: list[Path] = []
    for version_dir in profiles_root.iterdir():
        if not version_dir.is_dir():
            continue
        locale_dirs = [item for item in version_dir.iterdir() if item.is_dir()]
        for locale_dir in locale_dirs:
            startup_dir = locale_dir / "scripts" / "startup"
            # Only create startup folders inside a real 3ds Max profile.
            if not (locale_dir / "scripts").exists() and not startup_dir.exists():
                continue
            startup_dir.mkdir(parents=True, exist_ok=True)
            target = startup_dir / AUTO_STARTUP_FILENAME
            current = target.read_text(encoding="utf-8") if target.is_file() else ""
            if current != loader_text:
                target.write_text(loader_text, encoding="utf-8", newline="\n")
            installed.append(target)
    return installed


def project_root() -> Path:
    return Path(__file__).resolve().parents[3]


def send_command(command: str, timeout: float = 10.0) -> dict:
    with socket.create_connection((HOST, PORT), timeout=timeout) as sock:
        sock.sendall((command + "\n").encode("utf-8"))
        data = bytearray()
        while True:
            chunk = sock.recv(65536)
            if not chunk:
                break
            data.extend(chunk)
            if b"\n" in chunk:
                break
    raw = bytes(data).decode("utf-8", errors="replace").strip()
    if not raw:
        raise RuntimeError("3ds Max bridge returned an empty response.")
    try:
        return json.loads(raw)
    except json.JSONDecodeError as exc:
        raise RuntimeError("Invalid JSON from 3ds Max bridge: " + raw) from exc


def current_bridge_identity() -> tuple[str, str]:
    ping = send_command("PING", timeout=1.5)
    if not ping.get("ok"):
        return "", ""
    data = ping.get("data") or {}
    return (
        str(data.get("bridge_version") or ""),
        str(data.get("bridge_build_id") or ""),
    )


def current_version() -> str:
    return current_bridge_identity()[0]


def reload_current_bridge() -> dict:
    bridge_path = project_root() / "maxscripts" / "ForestManager_Bridge.ms"
    if not bridge_path.is_file():
        raise RuntimeError("Forest Manager bridge file not found: " + str(bridge_path))

    encoded = base64.b64encode(str(bridge_path).encode("utf-8")).decode("ascii")
    response = send_command("RELOAD_BRIDGE|" + encoded, timeout=5.0)
    if not response.get("ok"):
        raise RuntimeError("Bridge reload request failed: " + json.dumps(response, ensure_ascii=False))

    last_error = ""
    for _ in range(40):
        time.sleep(0.2)
        try:
            ping = send_command("PING", timeout=1.0)
            data = ping.get("data") or {}
            version = str(data.get("bridge_version") or "")
            build_id = str(data.get("bridge_build_id") or "")
            if (
                ping.get("ok")
                and version == EXPECTED_BRIDGE_VERSION
                and build_id == EXPECTED_BRIDGE_BUILD_ID
            ):
                return ping
            last_error = "bridge_version=" + version + ", bridge_build_id=" + build_id
        except Exception as exc:
            last_error = type(exc).__name__ + ": " + str(exc)
    raise RuntimeError("Bridge reload did not verify: " + last_error)


def ensure_current_bridge() -> dict:
    # Keep the next 3ds Max launch self-healing even when the current session is healthy.
    startup_paths = install_startup_bridge_loader()

    try:
        version, build_id = current_bridge_identity()
        if version == EXPECTED_BRIDGE_VERSION and build_id == EXPECTED_BRIDGE_BUILD_ID:
            return send_command("PING", timeout=1.5)
    except Exception:
        pass

    try:
        return reload_current_bridge()
    except Exception as exc:
        startup_note = ""
        if startup_paths:
            startup_note = " Automatic startup loader installed for: " + ", ".join(str(path) for path in startup_paths) + ". Restart 3ds Max once if no bridge is currently listening."
        raise RuntimeError(
            "Automatic bridge preflight failed." + startup_note + " Details: " + str(exc)
        ) from exc
